@startuml
skinparam componentStyle uml2
!pragma layout elk
  folder "jakarta.jakartaee-api" {
      [jakarta.platform:jakarta.jakartaee-api:jar:9.1.0] <<Artifact File Maven Platform Release>> as n256812
  }
  folder "jakarta.mail-api" {
      [jakarta.mail:jakarta.mail-api:jar:2.0.1] <<Artifact File Maven Release>> as n187795
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.1] <<Artifact File Maven>> as n187827
  }
  folder "jakarta.activation-api" {
      [jakarta.activation:jakarta.activation-api:jar:2.0.1] <<Artifact File Maven Release>> as n188165
  }
  folder "jakarta.jakartaee-web-api" {
      [jakarta.platform:jakarta.jakartaee-web-api:jar:9.1.0] <<Artifact File Maven Release>> as n255965
  }
  folder "jakarta.faces-api" {
      [jakarta.faces:jakarta.faces-api:jar:3.0.0] <<Artifact File Maven Release>> as n76827
  }
  folder "jakarta.json-api" {
      [jakarta.json:jakarta.json-api:jar:2.0.0] <<Artifact File Maven Release>> as n76828
  }
  folder "jakarta.faces" {
      [org.glassfish:jakarta.faces:jar:sources:3.0.0-RC5] <<Artifact File Maven>> as n235143
  }
  folder "jakarta.websocket-api" {
      [jakarta.websocket:jakarta.websocket-api:jar:2.0.0] <<Artifact File Maven>> as n88168
  }
  folder "jakarta.servlet.jsp.jstl-api" {
      [jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:jar:2.0.0] <<Artifact File Maven Release>> as n86756
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.servlet.jsp-api" {
      [jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.0.0] <<Artifact File Maven Release>> as n16689
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.xml.bind-api" {
      [jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.0] <<Artifact File Maven Release>> as n77295
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.0] <<Artifact File Maven>> as n78698
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "jakarta.persistence-api" {
      [jakarta.persistence:jakarta.persistence-api:jar:3.0.0] <<Artifact File Maven Release>> as n16690
  }
  folder "jakarta.xml.ws-api" {
      [jakarta.xml.ws:jakarta.xml.ws-api:jar:3.0.0] <<Artifact File Maven Release>> as n77296
  }
  folder "jakarta.xml.soap-api" {
      [jakarta.xml.soap:jakarta.xml.soap-api:jar:2.0.0] <<Artifact File Maven Release>> as n77297
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.0] <<Artifact File Maven>> as n78698
  }
  folder "junit" {
      [junit:junit:jar:4.12] <<Artifact File Maven>> as n4209
  }
  folder "jakarta.xml.bind-api" {
      [jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.0] <<Artifact File Maven Release>> as n77295
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.0] <<Artifact File Maven>> as n78698
  }
  folder "jakarta.jws-api" {
      [jakarta.jws:jakarta.jws-api:jar:3.0.0] <<Artifact File Maven Release>> as n16692
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0] <<Artifact File Maven Release>> as n7606
  }
  folder "jakarta.ejb-api" {
      [jakarta.ejb:jakarta.ejb-api:jar:4.0.0-RC2] <<Artifact File Maven Release>> as n5797
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n4843
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n5798
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0] <<Artifact File Maven Release>> as n7607
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0] <<Artifact File Maven Release>> as n7610
  }
  folder "jakarta.validation-api" {
      [jakarta.validation:jakarta.validation-api:jar:3.0.0] <<Artifact File Maven Release>> as n76830
  }
  folder "testng" {
      [org.testng:testng:jar:6.11] <<Artifact File Maven>> as n100954
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.xml.bind-api" {
      [jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.0] <<Artifact File Maven Release>> as n77295
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.0] <<Artifact File Maven>> as n78698
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.servlet.jsp-api" {
      [jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.0.0] <<Artifact File Maven Release>> as n16689
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.ejb-api" {
      [jakarta.ejb:jakarta.ejb-api:jar:4.0.0-RC2] <<Artifact File Maven Release>> as n5797
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n4843
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC3] <<Artifact File Maven Release>> as n176474
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0] <<Artifact File Maven Release>> as n7610
  }
  folder "jakarta.security.enterprise-api" {
      [jakarta.security.enterprise:jakarta.security.enterprise-api:jar:2.0.0] <<Artifact File Maven>> as n88170
  }
  folder "jakarta.websocket-api" {
      [jakarta.websocket:jakarta.websocket-api:jar:2.0.0] <<Artifact File Maven>> as n88168
  }
  folder "jakarta.faces" {
      [org.glassfish:jakarta.faces:jar:3.0.0] <<Artifact File Maven>> as n88171
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0] <<Artifact File Maven Release>> as n83560
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.servlet.jsp.jstl-api" {
      [jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:jar:2.0.0] <<Artifact File Maven Release>> as n86756
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.servlet.jsp-api" {
      [jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.0.0] <<Artifact File Maven Release>> as n16689
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.xml.bind-api" {
      [jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.0] <<Artifact File Maven Release>> as n77295
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.0] <<Artifact File Maven>> as n78698
  }
  folder "jakarta.persistence-api" {
      [jakarta.persistence:jakarta.persistence-api:jar:3.0.0] <<Artifact File Maven Release>> as n16690
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0] <<Artifact File Maven Release>> as n7607
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0] <<Artifact File Maven Release>> as n7606
  }
  folder "jakarta.ejb-api" {
      [jakarta.ejb:jakarta.ejb-api:jar:4.0.0-RC2] <<Artifact File Maven Release>> as n5797
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n4843
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n5798
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0] <<Artifact File Maven Release>> as n7607
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0] <<Artifact File Maven Release>> as n7610
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.json-api" {
      [jakarta.json:jakarta.json-api:jar:2.0.1] <<Artifact File Maven Release>> as n256006
  }
  folder "jakarta.servlet.jsp-api" {
      [jakarta.servlet.jsp:jakarta.servlet.jsp-api:jar:3.0.0] <<Artifact File Maven Release>> as n16689
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.json.bind-api" {
      [jakarta.json.bind:jakarta.json.bind-api:jar:2.0.0] <<Artifact File Maven Release>> as n76829
  }
  folder "junit" {
      [junit:junit:jar:4.12] <<Artifact File Maven>> as n4209
  }
  folder "jakarta.json-api" {
      [jakarta.json:jakarta.json-api:jar:2.0.0] <<Artifact File Maven Release>> as n76828
  }
  folder "jakarta.validation-api" {
      [jakarta.validation:jakarta.validation-api:jar:3.0.0] <<Artifact File Maven Release>> as n76830
  }
  folder "testng" {
      [org.testng:testng:jar:6.11] <<Artifact File Maven>> as n100954
  }
  folder "jakarta.ws.rs-api" {
      [jakarta.ws.rs:jakarta.ws.rs-api:jar:3.0.0] <<Artifact File Maven>> as n16691
  }
  folder "jakarta.ejb-api" {
      [jakarta.ejb:jakarta.ejb-api:jar:4.0.0] <<Artifact File Maven Release>> as n88169
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0] <<Artifact File Maven Release>> as n83560
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "jakarta.authentication-api" {
      [jakarta.authentication:jakarta.authentication-api:jar:2.0.0] <<Artifact File Maven Release>> as n79628
  }
  folder "jakarta.jws-api" {
      [jakarta.jws:jakarta.jws-api:jar:3.0.0] <<Artifact File Maven Release>> as n16692
  }
  folder "jakarta.enterprise.concurrent-api" {
      [jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api:jar:2.0.0] <<Artifact File Maven Release>> as n77293
  }
  folder "junit" {
      [junit:junit:jar:4.13] <<Artifact File Maven>> as n79629
  }
  folder "jakarta.authorization-api" {
      [jakarta.authorization:jakarta.authorization-api:jar:2.0.0] <<Artifact File Maven Release>> as n20657
  }
  folder "jakarta.servlet-api" {
      [jakarta.servlet:jakarta.servlet-api:jar:5.0.0] <<Artifact File Maven Release>> as n7609
  }
  folder "jakarta.jms-api" {
      [jakarta.jms:jakarta.jms-api:jar:3.0.0] <<Artifact File Maven Release>> as n84426
  }
  folder "jakarta.resource-api" {
      [jakarta.resource:jakarta.resource-api:jar:2.0.0] <<Artifact File Maven Release>> as n87202
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n4843
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.xml.bind-api" {
      [jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1] <<Artifact File Maven Release>> as n206264
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.1] <<Artifact File Maven>> as n187827
  }
  folder "jakarta.mail" {
      [com.sun.mail:jakarta.mail:jar:2.0.1] <<Artifact File Maven>> as n187829
  }
  folder "jakarta.batch-api" {
      [jakarta.batch:jakarta.batch-api:jar:2.0.0] <<Artifact File Maven Release>> as n77294
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0] <<Artifact File Maven Release>> as n7606
  }
  folder "jakarta.ejb-api" {
      [jakarta.ejb:jakarta.ejb-api:jar:4.0.0-RC2] <<Artifact File Maven Release>> as n5797
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n4843
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.transaction-api" {
      [jakarta.transaction:jakarta.transaction-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n5798
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.enterprise.cdi-api" {
      [jakarta.enterprise:jakarta.enterprise.cdi-api:jar:3.0.0-M1] <<Artifact File Maven Release>> as n27697
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0-RC1] <<Artifact File Maven Release>> as n51935
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:1.3.5] <<Artifact File Maven Release>> as n40422
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0-RC2] <<Artifact File Maven Release>> as n71724
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0-RC1] <<Artifact File Maven Release>> as n553
  }
  folder "jakarta.interceptor-api" {
      [jakarta.interceptor:jakarta.interceptor-api:jar:2.0.0] <<Artifact File Maven Release>> as n7607
  }
  folder "jakarta.annotation-api" {
      [jakarta.annotation:jakarta.annotation-api:jar:2.0.0] <<Artifact File Maven Release>> as n7608
  }
  folder "testng" {
      [org.testng:testng:jar:6.8.8] <<Artifact File Maven>> as n16336
  }
  folder "jakarta.el-api" {
      [jakarta.el:jakarta.el-api:jar:4.0.0] <<Artifact File Maven Release>> as n7611
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0] <<Artifact File Maven Release>> as n7610
  }
  folder "jakarta.inject-api" {
      [jakarta.inject:jakarta.inject-api:jar:2.0.0] <<Artifact File Maven Release>> as n7610
  }
  folder "jakarta.xml.ws-api" {
      [jakarta.xml.ws:jakarta.xml.ws-api:jar:3.0.1] <<Artifact File Maven Release>> as n206238
  }
  folder "jakarta.xml.soap-api" {
      [jakarta.xml.soap:jakarta.xml.soap-api:jar:2.0.1] <<Artifact File Maven Release>> as n206265
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.1] <<Artifact File Maven>> as n187827
  }
  folder "junit" {
      [junit:junit:jar:4.13.2] <<Artifact File Maven>> as n187487
  }
  folder "jakarta.jws-api" {
      [jakarta.jws:jakarta.jws-api:jar:3.0.0] <<Artifact File Maven Release>> as n16692
  }
  folder "jakarta.xml.bind-api" {
      [jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1] <<Artifact File Maven Release>> as n206264
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.1] <<Artifact File Maven>> as n187827
  }
  folder "jakarta.faces" {
      [org.glassfish:jakarta.faces:jar:3.0.0] <<Artifact File Maven>> as n88171
  }
  folder "jakarta.xml.soap-api" {
      [jakarta.xml.soap:jakarta.xml.soap-api:jar:2.0.1] <<Artifact File Maven Release>> as n206265
  }
  folder "jakarta.activation" {
      [com.sun.activation:jakarta.activation:jar:2.0.1] <<Artifact File Maven>> as n187827
  }
  folder "junit" {
      [junit:junit:jar:4.13.2] <<Artifact File Maven>> as n187487
  }

n256812 --> n187795 : depends on (scope:compile, optional:true)
n187795 --> n187827 : depends on (scope:provided, optional:false)
n256812 --> n188165 : depends on (scope:compile, optional:true)
n256812 --> n255965 : depends on (scope:compile, optional:true)
n255965 --> n76827 : depends on (scope:compile, optional:true)
n76827 --> n76828 : depends on (scope:provided, optional:true)
n76827 --> n235143 : depends on (scope:provided, optional:false)
n76827 --> n88168 : depends on (scope:provided, optional:false)
n76827 --> n86756 : depends on (scope:provided, optional:true)
n86756 --> n7609 : depends on (scope:compile, optional:false)
n86756 --> n16689 : depends on (scope:provided, optional:false)
n16689 --> n7611 : depends on (scope:provided, optional:false)
n16689 --> n7609 : depends on (scope:provided, optional:false)
n86756 --> n7611 : depends on (scope:compile, optional:false)
n86756 --> n77295 : depends on (scope:compile, optional:false)
n77295 --> n78698 : depends on (scope:compile, optional:false)
n76827 --> n7608 : depends on (scope:provided, optional:false)
n76827 --> n16690 : depends on (scope:provided, optional:true)
n76827 --> n77296 : depends on (scope:provided, optional:true)
n77296 --> n77297 : depends on (scope:compile, optional:false)
n77297 --> n78698 : depends on (scope:compile, optional:false)
n77297 --> n4209 : depends on (scope:test, optional:false)
n77296 --> n77295 : depends on (scope:compile, optional:false)
n77296 --> n16692 : depends on (scope:compile, optional:false)
n76827 --> n7606 : depends on (scope:provided, optional:false)
n7606 --> n5797 : depends on (scope:provided, optional:false)
n5797 --> n4843 : depends on (scope:compile, optional:false)
n4843 --> n51935 : depends on (scope:provided, optional:false)
n51935 --> n40422 : depends on (scope:compile, optional:false)
n4843 --> n27697 : depends on (scope:provided, optional:false)
n27697 --> n16336 : depends on (scope:test, optional:false)
n27697 --> n51935 : depends on (scope:compile, optional:false)
n27697 --> n71724 : depends on (scope:compile, optional:false)
n27697 --> n553 : depends on (scope:compile, optional:false)
n7606 --> n5798 : depends on (scope:provided, optional:false)
n5798 --> n51935 : depends on (scope:provided, optional:false)
n5798 --> n27697 : depends on (scope:provided, optional:false)
n7606 --> n7607 : depends on (scope:compile, optional:false)
n7607 --> n7608 : depends on (scope:compile, optional:false)
n7606 --> n16336 : depends on (scope:test, optional:false)
n7606 --> n7611 : depends on (scope:compile, optional:false)
n7606 --> n7610 : depends on (scope:compile, optional:false)
n76827 --> n76830 : depends on (scope:provided, optional:false)
n76830 --> n100954 : depends on (scope:test, optional:false)
n76827 --> n7611 : depends on (scope:provided, optional:false)
n76827 --> n77295 : depends on (scope:provided, optional:true)
n76827 --> n7609 : depends on (scope:provided, optional:false)
n76827 --> n16689 : depends on (scope:provided, optional:true)
n76827 --> n5797 : depends on (scope:provided, optional:true)
n76827 --> n176474 : depends on (scope:provided, optional:true)
n176474 --> n51935 : depends on (scope:provided, optional:false)
n176474 --> n27697 : depends on (scope:provided, optional:false)
n255965 --> n7610 : depends on (scope:compile, optional:true)
n255965 --> n88170 : depends on (scope:compile, optional:true)
n255965 --> n88168 : depends on (scope:compile, optional:true)
n255965 --> n88171 : depends on (scope:compile, optional:true)
n255965 --> n83560 : depends on (scope:compile, optional:true)
n83560 --> n51935 : depends on (scope:provided, optional:false)
n83560 --> n27697 : depends on (scope:provided, optional:false)
n255965 --> n86756 : depends on (scope:compile, optional:true)
n255965 --> n16690 : depends on (scope:compile, optional:true)
n255965 --> n7607 : depends on (scope:compile, optional:true)
n255965 --> n7606 : depends on (scope:compile, optional:true)
n255965 --> n7609 : depends on (scope:compile, optional:true)
n255965 --> n256006 : depends on (scope:compile, optional:true)
n255965 --> n16689 : depends on (scope:compile, optional:true)
n255965 --> n7611 : depends on (scope:compile, optional:true)
n255965 --> n76829 : depends on (scope:compile, optional:true)
n76829 --> n4209 : depends on (scope:test, optional:false)
n76829 --> n76828 : depends on (scope:provided, optional:false)
n255965 --> n76830 : depends on (scope:compile, optional:true)
n255965 --> n16691 : depends on (scope:compile, optional:true)
n255965 --> n88169 : depends on (scope:compile, optional:true)
n88169 --> n83560 : depends on (scope:compile, optional:false)
n255965 --> n7608 : depends on (scope:compile, optional:true)
n255965 --> n79628 : depends on (scope:compile, optional:true)
n256812 --> n16692 : depends on (scope:compile, optional:true)
n256812 --> n77293 : depends on (scope:compile, optional:true)
n77293 --> n79629 : depends on (scope:test, optional:false)
n256812 --> n20657 : depends on (scope:compile, optional:true)
n20657 --> n7609 : depends on (scope:compile, optional:false)
n256812 --> n84426 : depends on (scope:compile, optional:true)
n256812 --> n87202 : depends on (scope:compile, optional:true)
n87202 --> n7608 : depends on (scope:compile, optional:false)
n87202 --> n4843 : depends on (scope:compile, optional:false)
n256812 --> n206264 : depends on (scope:compile, optional:true)
n206264 --> n187827 : depends on (scope:compile, optional:false)
n256812 --> n187829 : depends on (scope:compile, optional:true)
n256812 --> n77294 : depends on (scope:compile, optional:true)
n77294 --> n7606 : depends on (scope:provided, optional:false)
n77294 --> n7610 : depends on (scope:provided, optional:false)
n256812 --> n206238 : depends on (scope:compile, optional:true)
n206238 --> n206265 : depends on (scope:compile, optional:false)
n206265 --> n187827 : depends on (scope:compile, optional:false)
n206265 --> n187487 : depends on (scope:test, optional:false)
n206238 --> n16692 : depends on (scope:compile, optional:false)
n206238 --> n206264 : depends on (scope:compile, optional:false)
n256812 --> n88171 : depends on (scope:compile, optional:true)
n256812 --> n206265 : depends on (scope:compile, optional:true)

@enduml
