= Jakarta EE Dependency Analysis With jQAssistant

== Overview

This project provides a setup to scan Maven Central repository for Jakarta EE artifacts and provide reports about dependencies of the involved specifications.

== Requirements

* Java Development Kit 8 or 11
* Maven 3.5.x or later

== How To Use It

* Clone the project
* Execute the following command
+
----
mvn verify -Drepo.url=http://host:8080/nexus/content/repositories/my-repo -Drepo.filter=com.my-company.*:*:*"
----
+
NOTE: The first scan fetches the full index from Maven Central, this will take time.
* After analysis the following reports are created in the folder `target/jqassistant/report`:
** `plantuml/jakarta-ee-dependencies_PlatformDependencyReport.plantuml`: The dependencies as PlantUML component diagram
** `plantuml/jakarta-ee-dependencies_PlatformDependencyReport.svg`: The rendered PlantUML diagram converted to SVG
** `graphml/jakarta-ee-dependencies_PlatformDependencyReport.graphml`: The dependencies as GraphML file.
+
TIP: GraphML reports may be viewed using https://www.yworks.com/en/products/yfiles/yed/[yEd]. After opening a file you should apply a layout, e.g. `Layout->Hierarchical` (Alt-Shift-H) and property mapping (`Edit->Properties Mapper`) for nodes should be set to use `fqn` as `Label Text`.
  +
An Open Source alternative is https://gephi.org/[Gephi]. After opening the file `Show Node label(s)` must be activated in the tool palette at the bottom and `fqn` selected in `Attributes` to be displayed as node label.

== Known Issues

* The scan and queries used for analysis might be expensive. If an OutOfMemoryError is reported then the heap size for Maven should be set using the environment variable, e.g. `MAVEN_OPTS=-Xmx16G`.
